(function() {var implementors = {};
implementors["rusttype"] = ["impl&lt;N: <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='rusttype/struct.Point.html' title='rusttype::Point'>Point</a>&lt;N&gt;","impl&lt;N: <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='rusttype/struct.Vector.html' title='rusttype::Vector'>Vector</a>&lt;N&gt;","impl&lt;N: <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='rusttype/struct.Rect.html' title='rusttype::Rect'>Rect</a>&lt;N&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='rusttype/gpu_cache/enum.CacheReadErr.html' title='rusttype::gpu_cache::CacheReadErr'>CacheReadErr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='rusttype/gpu_cache/enum.CacheWriteErr.html' title='rusttype::gpu_cache::CacheWriteErr'>CacheWriteErr</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='rusttype/struct.Codepoint.html' title='rusttype::Codepoint'>Codepoint</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='enum' href='rusttype/enum.CodepointOrGlyphId.html' title='rusttype::CodepointOrGlyphId'>CodepointOrGlyphId</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='rusttype/struct.GlyphId.html' title='rusttype::GlyphId'>GlyphId</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
